-- ==========================================================
-- SCRIPT DE INICIALIZACIÓN DE BASE DE DATOS (SUPABASE)
-- Copia y pega todo este código en el SQL Editor de tu Supabase
-- ==========================================================

-- 1. Crear la tabla de productos
CREATE TABLE IF NOT EXISTS productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text NOT NULL,
  precio numeric NOT NULL,
  precio_antiguo numeric, -- Para tachar en ofertas
  sku text UNIQUE NOT NULL,
  dropi_id text, -- ID en Dropi para automatización
  imagenes text[] NOT NULL, -- Array de URLs de imágenes
  opciones jsonb DEFAULT '[]'::jsonb, -- Tallas o colores, ej. ["38", "39", "40"]
  slug text UNIQUE NOT NULL, -- URL amigable, ej. "tenis-ultracomfort"
  beneficios jsonb DEFAULT '[]'::jsonb, -- Características del producto
  testimonios jsonb DEFAULT '[]'::jsonb, -- Reseñas de clientes
  activo boolean DEFAULT true,
  fecha timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Modificar la tabla de pedidos existente para soportar múltiples productos e integración con Dropi
-- Nota: Usamos ALTER TABLE y manejamos si ya existen las columnas
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS productos_json jsonb DEFAULT '[]'::jsonb;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS dropi_status text DEFAULT 'Pendiente API';
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS error_log text;

-- 3. Habilitar la seguridad a nivel de fila (Row Level Security - RLS)
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas de seguridad para la tabla productos
-- Permitir que cualquier usuario pueda ver los productos (Lectura pública)
DROP POLICY IF EXISTS "Permitir lectura pública de productos" ON productos;
CREATE POLICY "Permitir lectura pública de productos" ON productos
  FOR SELECT TO public USING (true);

-- Permitir control total de productos solo a través de la API (Service Role Key)
DROP POLICY IF EXISTS "Permitir gestión de productos al rol de servicio" ON productos;
CREATE POLICY "Permitir gestión de productos al rol de servicio" ON productos
  FOR ALL TO service_role USING (true);

-- 5. Crear políticas de seguridad adicionales para la tabla pedidos (si no existen)
-- Asegurar que el rol de servicio (backend) pueda leer y actualizar pedidos
DROP POLICY IF EXISTS "Permitir lectura para el rol de servicio" ON pedidos;
CREATE POLICY "Permitir lectura para el rol de servicio" ON pedidos
  FOR SELECT TO service_role USING (true);

DROP POLICY IF EXISTS "Permitir actualización para el rol de servicio" ON pedidos;
CREATE POLICY "Permitir actualización para el rol de servicio" ON pedidos
  FOR UPDATE TO service_role USING (true);
