-- Crear la tabla anuncios_espia para el rastreo y análisis de productos ganadores
CREATE TABLE IF NOT EXISTS anuncios_espia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_id VARCHAR(255) UNIQUE NOT NULL,
  page_name VARCHAR(255) NOT NULL,
  start_date TIMESTAMP WITH TIME ZONE NOT NULL,
  days_active INT NOT NULL,
  copy_text TEXT,
  creative_url TEXT,
  ad_link TEXT,
  competencia VARCHAR(50) DEFAULT 'Baja',
  oportunidad TEXT,
  diagnostico_copy TEXT,
  copy_mejorado TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar permisos de lectura y escritura para la API anónima
ALTER TABLE anuncios_espia ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura pública de anuncios" 
ON anuncios_espia FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserción pública de anuncios" 
ON anuncios_espia FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir eliminación pública de anuncios"
ON anuncios_espia FOR DELETE
USING (true);
